version: 2
jobs:
  load_places:
    docker:
      - image: firstdraftgis/base:latest
    steps:
      - checkout
      - run: bash /firstdraft/build_steps/1-load_places
        
  load_training_data:
    docker:
      - image: firstdraftgis/loaded:latest
    steps:
      - run:
          name: Update Source Code and Database (if necessary)
          command: |
            cd /firstdraft
            git pull
            python3 manage.py makemigrations
            python3 manage.py migrate
      - run:
          name: Download Genesis Training Data
          command: |
            cd /tmp
            wget --no-verbose https://s3.amazonaws.com/firstdraftgis/genesis.tsv.zip
            unzip genesis.tsv.zip
            rm genesis.tsv.zip
      - run:
          name: Conform Training Data
          command: |
            cd /firstdraft
            python3 manage.py runscript conform.training_data
  publish:
    docker:
      - image: python:latest
    steps:
      - run: echo "finished"
workflows:
  version: 2
  full_build:
    jobs:
      - load_places
      - load_training_data:
          requires:
            - load_places
        

